/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agconnectclouddb.objecttypes;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType gallery_user_puzzle.
 *
 * @since 2024-11-30
 */
@PrimaryKeys({"id"})
public final class gallery_user_puzzle extends CloudDBZoneObject {
    private String id;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean is_get;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean is_stick;

    private String external;

    @NotNull
    @DefaultValue(stringValue = "")
    private String create_time;

    @NotNull
    @DefaultValue(stringValue = "")
    private String update_time;

    private String id_puzzle;

    public gallery_user_puzzle() {
        super(gallery_user_puzzle.class);
        this.is_get = false;
        this.is_stick = false;
        this.create_time = "";
        this.update_time = "";
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setIs_get(Boolean is_get) {
        this.is_get = is_get;
    }

    public Boolean getIs_get() {
        return is_get;
    }

    public void setIs_stick(Boolean is_stick) {
        this.is_stick = is_stick;
    }

    public Boolean getIs_stick() {
        return is_stick;
    }

    public void setExternal(String external) {
        this.external = external;
    }

    public String getExternal() {
        return external;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setUpdate_time(String update_time) {
        this.update_time = update_time;
    }

    public String getUpdate_time() {
        return update_time;
    }

    public void setId_puzzle(String id_puzzle) {
        this.id_puzzle = id_puzzle;
    }

    public String getId_puzzle() {
        return id_puzzle;
    }

}
