/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agconnectclouddb.objecttypes;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType gallery_system.
 *
 * @since 2025-01-09
 */
@PrimaryKeys({"id"})
public final class gallery_system extends CloudDBZoneObject {
    private String id;

    private String image_url;

    private Integer count_piece;

    @DefaultValue(booleanValue = false)
    private Boolean is_delete;

    private String external;

    private Text image_detail;

    public gallery_system() {
        super(gallery_system.class);
        this.is_delete = false;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setCount_piece(Integer count_piece) {
        this.count_piece = count_piece;
    }

    public Integer getCount_piece() {
        return count_piece;
    }

    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    public Boolean getIs_delete() {
        return is_delete;
    }

    public void setExternal(String external) {
        this.external = external;
    }

    public String getExternal() {
        return external;
    }

    public void setImage_detail(Text image_detail) {
        this.image_detail = image_detail;
    }

    public Text getImage_detail() {
        return image_detail;
    }

}
