/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agconnectclouddb.objecttypes;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType gallery_user.
 *
 * @since 2025-01-09
 */
@PrimaryKeys({"id"})
public final class gallery_user extends CloudDBZoneObject {
    private String id;

    @NotNull
    @DefaultValue(stringValue = "")
    private String id_puzzle;

    private Integer count_piece;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean is_lock;

    private String external;

    @NotNull
    @DefaultValue(stringValue = "")
    private String create_time;

    private String union_id;

    public gallery_user() {
        super(gallery_user.class);
        this.id_puzzle = "";
        this.is_lock = false;
        this.create_time = "";
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setId_puzzle(String id_puzzle) {
        this.id_puzzle = id_puzzle;
    }

    public String getId_puzzle() {
        return id_puzzle;
    }

    public void setCount_piece(Integer count_piece) {
        this.count_piece = count_piece;
    }

    public Integer getCount_piece() {
        return count_piece;
    }

    public void setIs_lock(Boolean is_lock) {
        this.is_lock = is_lock;
    }

    public Boolean getIs_lock() {
        return is_lock;
    }

    public void setExternal(String external) {
        this.external = external;
    }

    public String getExternal() {
        return external;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setUnion_id(String union_id) {
        this.union_id = union_id;
    }

    public String getUnion_id() {
        return union_id;
    }

}
