/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agconnectclouddb.objecttypes;

import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType setting.
 *
 * @since 2024-10-06
 */
@PrimaryKeys({"union_id"})
public final class setting extends CloudDBZoneObject {
    private String union_id;

    private String language;

    private String theme;

    private String icon;

    private String start_day;

    private String notification_1;

    private String notification_2;

    private String notification_3;

    private String notification_4;

    private String sound_1;

    private String sound_2;

    private String extend;

    private String create_time;

    public setting() {
        super(setting.class);
    }

    public void setUnion_id(String union_id) {
        this.union_id = union_id;
    }

    public String getUnion_id() {
        return union_id;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getLanguage() {
        return language;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }

    public String getTheme() {
        return theme;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getIcon() {
        return icon;
    }

    public void setStart_day(String start_day) {
        this.start_day = start_day;
    }

    public String getStart_day() {
        return start_day;
    }

    public void setNotification_1(String notification_1) {
        this.notification_1 = notification_1;
    }

    public String getNotification_1() {
        return notification_1;
    }

    public void setNotification_2(String notification_2) {
        this.notification_2 = notification_2;
    }

    public String getNotification_2() {
        return notification_2;
    }

    public void setNotification_3(String notification_3) {
        this.notification_3 = notification_3;
    }

    public String getNotification_3() {
        return notification_3;
    }

    public void setNotification_4(String notification_4) {
        this.notification_4 = notification_4;
    }

    public String getNotification_4() {
        return notification_4;
    }

    public void setSound_1(String sound_1) {
        this.sound_1 = sound_1;
    }

    public String getSound_1() {
        return sound_1;
    }

    public void setSound_2(String sound_2) {
        this.sound_2 = sound_2;
    }

    public String getSound_2() {
        return sound_2;
    }

    public void setExtend(String extend) {
        this.extend = extend;
    }

    public String getExtend() {
        return extend;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getCreate_time() {
        return create_time;
    }

}
